[theme]
base="dark"
primaryColor="#FFFC4B"

[server]
enableXsrfProtection = true
#sslCertFile = '/path/to/certchain.pem'
#sslKeyFile = '/path/to/private.key'

[browser]
gatherUsageStats = false