version: '3'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${CLOUDFLARE_TOKEN}
    container_name: cloudflared
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.2

  drawio:
    image: jgraph/drawio:latest
    container_name: drawio_container
    ports:
      - "8443:8443"
    environment:
      - PUBLIC_DNS=drawio.elatedmaniac.io
      - LETS_ENCRYPT_ENABLED=true
    networks:
      default:
        ipv4_address: 172.18.0.3

  anaconda:
    build:
      context: .
      dockerfile: Jupyter/Dockerfile
    container_name: anaconda_container
    ports:
      - "8888:8888"
    volumes:
      - ./Jupyter/certs:/home/jupyter/.jupyter/ssl
      - ./Jupyter/data:/workspace
      - ./Jupyter/config/jupyter_application_config.py/:/home/jupyter/.jupyter/jupyter_application_config.py
      - ./logs:/workspace/logs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      default:
        ipv4_address: 172.18.0.4
  phi3:
    build:
      context: .
      dockerfile: ollama/Dockerfile
      args:
      - MODEL=${MODEL:-phi3:3.8b} 
    container_name: phi3
    environment:
      - MODEL=${MODEL:-phi3:3.8b}
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/data:/root/.ollama  
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.5

  neo4j:
    build:
      context: ./neo4j
      args:
        NEO4J_AUTH: ${NEO4J_AUTH}
    container_name: neo4j_container
    ports:
      - "7474:7474"   # HTTP
      - "7473:7473"   # HTTPS
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS=${NEO4J_PLUGINS}
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/certificates:/var/lib/neo4j/certificates
    networks:
      default:
        ipv4_address: 172.18.0.6

  nginx:
    build:
      context: ./Nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certificates:/etc/nginx/certificates
    depends_on:
      - anaconda
      - drawio
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.7
  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit/app:/app
      - ./streamlit/app/.streamlit:/root/.streamlit 
    networks:
      default:
        ipv4_address: 172.18.0.8
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    networks:
      default:
        ipv4_address: 172.18.0.10

volumes:
  postgres-db-volume:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
